require 'rails_helper'
require 'rubygems'

p "rspec_helper RAILS_ENV = #{ENV['RAILS_ENV']}"
# This file was generated by the `rails generate rspec:install` command.

# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    # Prevents mocking or stubbing a method that does not exist on a real object.
    mocks.verify_partial_doubles = true
  end

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # These two settings work together to allow you to limit a spec run
  # to individual examples or groups you care about by tagging them with
  # `:focus` metadata. When nothing is tagged with `:focus`, all examples
  # get run.
  config.filter_run :focus
  config.run_all_when_everything_filtered = true

  config.disable_monkey_patching!

  if config.files_to_run.one?
    config.default_formatter = 'doc'
  end

  # Print the 10 slowest examples/groups at the end of the spec run.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies.
  # Order can be fixed by specifying the seed, which is printed after each run.
  #    --seed 1234
  config.order = :random
  Kernel.srand config.seed
=end
end
